### ISSUE TITLE
确认下述指令的实际含义，并实现

### ISSUE THREAD

**Issue by roastduck** [oscourse-tsinghua/OS2018spring-projects-g05#3]
通过`mipsel-linux-gnu-objdump -d vmlinux | less`可以发现下述未能辨别的指令。请手动翻译机器码，确认其实际对应的指令，并实现

```
bc0t
bc0fl
c0
ehb
jr.hb
cfc0
ldc3
negu
sdc3
```

**Comment by XemboLiu** [comment]
最新版本的指令集见：https://www.mips.com/?do-download=the-mips32-instruction-set-v6-06

bc0t：未能找到满足高12位可能是0x410的指令
bc0fl：未能找到满足高12位可能是0x410的指令
c0 0x4：这条指令实际上是 TLBINVF
ehb：有这条指令
jr.hb：有这条指令
cfc0 mfhc0：直接返回0即可（注：release6之前未定义，release6的文档中要求其将相应的寄存器置0）
ldc3：没有找到”110111”开头的指令
negu：实际上是特殊的subu指令
sdc3：未找到二进制为”111111”开头的指令
